apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
  - nodePort: 30955
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  type: NodePort