apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb
  targetCPUUtilizationPercentage: 80
