apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongoauctiondetails
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongoauctiondetails
  targetCPUUtilizationPercentage: 80