apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auctionroommanager
  name: auctionroommanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctionroommanager
  template:
    metadata:
      labels:
        app: auctionroommanager
    spec:
      containers:
          - image: gcr.io/graphical-mile-329010/auctionbackend-auctionroommanager:1.0
            imagePullPolicy: Always
            name: auctionbackend-auctionroommanager
            ports:
            - containerPort: 9000
              protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auctionroommanager
  name: auctionroommanager
  namespace: default
spec:
  ports:
  - nodePort: 30199
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: auctionroommanager
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auctionroommanager
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auctionroommanager
  targetCPUUtilizationPercentage: 80
  